/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HubRouteImport } from './routes/hub'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubIndexRouteImport } from './routes/hub.index'
import { Route as DemandesIndexRouteImport } from './routes/demandes.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HubReceptionRouteImport } from './routes/hub.reception'
import { Route as HubParcelsRouteImport } from './routes/hub.parcels'
import { Route as DemandesIdRouteImport } from './routes/demandes.$id'
import { Route as AdminScanRouteImport } from './routes/admin.scan'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminParcelsRouteImport } from './routes/admin.parcels'
import { Route as AdminDemandesRouteImport } from './routes/admin.demandes'
import { Route as HubValisesIndexRouteImport } from './routes/hub.valises.index'
import { Route as AdminScanIndexRouteImport } from './routes/admin.scan.index'
import { Route as AdminDemandesIndexRouteImport } from './routes/admin.demandes.index'
import { Route as HubValisesIdRouteImport } from './routes/hub.valises.$id'
import { Route as AdminScanMatchRouteImport } from './routes/admin.scan.match'
import { Route as AdminDemandesIdRouteImport } from './routes/admin.demandes.$id'

const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRoute,
} as any)
const DemandesIndexRoute = DemandesIndexRouteImport.update({
  id: '/demandes/',
  path: '/demandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HubReceptionRoute = HubReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => HubRoute,
} as any)
const HubParcelsRoute = HubParcelsRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => HubRoute,
} as any)
const DemandesIdRoute = DemandesIdRouteImport.update({
  id: '/demandes/$id',
  path: '/demandes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScanRoute = AdminScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParcelsRoute = AdminParcelsRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemandesRoute = AdminDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AdminRoute,
} as any)
const HubValisesIndexRoute = HubValisesIndexRouteImport.update({
  id: '/valises/',
  path: '/valises/',
  getParentRoute: () => HubRoute,
} as any)
const AdminScanIndexRoute = AdminScanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminScanRoute,
} as any)
const AdminDemandesIndexRoute = AdminDemandesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDemandesRoute,
} as any)
const HubValisesIdRoute = HubValisesIdRouteImport.update({
  id: '/valises/$id',
  path: '/valises/$id',
  getParentRoute: () => HubRoute,
} as any)
const AdminScanMatchRoute = AdminScanMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AdminScanRoute,
} as any)
const AdminDemandesIdRoute = AdminDemandesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDemandesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/hub': typeof HubRouteWithChildren
  '/admin/demandes': typeof AdminDemandesRouteWithChildren
  '/admin/parcels': typeof AdminParcelsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/scan': typeof AdminScanRouteWithChildren
  '/demandes/$id': typeof DemandesIdRoute
  '/hub/parcels': typeof HubParcelsRoute
  '/hub/reception': typeof HubReceptionRoute
  '/admin/': typeof AdminIndexRoute
  '/demandes/': typeof DemandesIndexRoute
  '/hub/': typeof HubIndexRoute
  '/admin/demandes/$id': typeof AdminDemandesIdRoute
  '/admin/scan/match': typeof AdminScanMatchRoute
  '/hub/valises/$id': typeof HubValisesIdRoute
  '/admin/demandes/': typeof AdminDemandesIndexRoute
  '/admin/scan/': typeof AdminScanIndexRoute
  '/hub/valises/': typeof HubValisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/parcels': typeof AdminParcelsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/hub/parcels': typeof HubParcelsRoute
  '/hub/reception': typeof HubReceptionRoute
  '/admin': typeof AdminIndexRoute
  '/demandes': typeof DemandesIndexRoute
  '/hub': typeof HubIndexRoute
  '/admin/demandes/$id': typeof AdminDemandesIdRoute
  '/admin/scan/match': typeof AdminScanMatchRoute
  '/hub/valises/$id': typeof HubValisesIdRoute
  '/admin/demandes': typeof AdminDemandesIndexRoute
  '/admin/scan': typeof AdminScanIndexRoute
  '/hub/valises': typeof HubValisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/hub': typeof HubRouteWithChildren
  '/admin/demandes': typeof AdminDemandesRouteWithChildren
  '/admin/parcels': typeof AdminParcelsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/scan': typeof AdminScanRouteWithChildren
  '/demandes/$id': typeof DemandesIdRoute
  '/hub/parcels': typeof HubParcelsRoute
  '/hub/reception': typeof HubReceptionRoute
  '/admin/': typeof AdminIndexRoute
  '/demandes/': typeof DemandesIndexRoute
  '/hub/': typeof HubIndexRoute
  '/admin/demandes/$id': typeof AdminDemandesIdRoute
  '/admin/scan/match': typeof AdminScanMatchRoute
  '/hub/valises/$id': typeof HubValisesIdRoute
  '/admin/demandes/': typeof AdminDemandesIndexRoute
  '/admin/scan/': typeof AdminScanIndexRoute
  '/hub/valises/': typeof HubValisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/hub'
    | '/admin/demandes'
    | '/admin/parcels'
    | '/admin/profile'
    | '/admin/scan'
    | '/demandes/$id'
    | '/hub/parcels'
    | '/hub/reception'
    | '/admin/'
    | '/demandes/'
    | '/hub/'
    | '/admin/demandes/$id'
    | '/admin/scan/match'
    | '/hub/valises/$id'
    | '/admin/demandes/'
    | '/admin/scan/'
    | '/hub/valises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/parcels'
    | '/admin/profile'
    | '/demandes/$id'
    | '/hub/parcels'
    | '/hub/reception'
    | '/admin'
    | '/demandes'
    | '/hub'
    | '/admin/demandes/$id'
    | '/admin/scan/match'
    | '/hub/valises/$id'
    | '/admin/demandes'
    | '/admin/scan'
    | '/hub/valises'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/hub'
    | '/admin/demandes'
    | '/admin/parcels'
    | '/admin/profile'
    | '/admin/scan'
    | '/demandes/$id'
    | '/hub/parcels'
    | '/hub/reception'
    | '/admin/'
    | '/demandes/'
    | '/hub/'
    | '/admin/demandes/$id'
    | '/admin/scan/match'
    | '/hub/valises/$id'
    | '/admin/demandes/'
    | '/admin/scan/'
    | '/hub/valises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HubRoute: typeof HubRouteWithChildren
  DemandesIdRoute: typeof DemandesIdRoute
  DemandesIndexRoute: typeof DemandesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/demandes/': {
      id: '/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof DemandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/hub/reception': {
      id: '/hub/reception'
      path: '/reception'
      fullPath: '/hub/reception'
      preLoaderRoute: typeof HubReceptionRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/parcels': {
      id: '/hub/parcels'
      path: '/parcels'
      fullPath: '/hub/parcels'
      preLoaderRoute: typeof HubParcelsRouteImport
      parentRoute: typeof HubRoute
    }
    '/demandes/$id': {
      id: '/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/demandes/$id'
      preLoaderRoute: typeof DemandesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scan': {
      id: '/admin/scan'
      path: '/scan'
      fullPath: '/admin/scan'
      preLoaderRoute: typeof AdminScanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parcels': {
      id: '/admin/parcels'
      path: '/parcels'
      fullPath: '/admin/parcels'
      preLoaderRoute: typeof AdminParcelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demandes': {
      id: '/admin/demandes'
      path: '/demandes'
      fullPath: '/admin/demandes'
      preLoaderRoute: typeof AdminDemandesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/hub/valises/': {
      id: '/hub/valises/'
      path: '/valises'
      fullPath: '/hub/valises/'
      preLoaderRoute: typeof HubValisesIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/admin/scan/': {
      id: '/admin/scan/'
      path: '/'
      fullPath: '/admin/scan/'
      preLoaderRoute: typeof AdminScanIndexRouteImport
      parentRoute: typeof AdminScanRoute
    }
    '/admin/demandes/': {
      id: '/admin/demandes/'
      path: '/'
      fullPath: '/admin/demandes/'
      preLoaderRoute: typeof AdminDemandesIndexRouteImport
      parentRoute: typeof AdminDemandesRoute
    }
    '/hub/valises/$id': {
      id: '/hub/valises/$id'
      path: '/valises/$id'
      fullPath: '/hub/valises/$id'
      preLoaderRoute: typeof HubValisesIdRouteImport
      parentRoute: typeof HubRoute
    }
    '/admin/scan/match': {
      id: '/admin/scan/match'
      path: '/match'
      fullPath: '/admin/scan/match'
      preLoaderRoute: typeof AdminScanMatchRouteImport
      parentRoute: typeof AdminScanRoute
    }
    '/admin/demandes/$id': {
      id: '/admin/demandes/$id'
      path: '/$id'
      fullPath: '/admin/demandes/$id'
      preLoaderRoute: typeof AdminDemandesIdRouteImport
      parentRoute: typeof AdminDemandesRoute
    }
  }
}

interface AdminDemandesRouteChildren {
  AdminDemandesIdRoute: typeof AdminDemandesIdRoute
  AdminDemandesIndexRoute: typeof AdminDemandesIndexRoute
}

const AdminDemandesRouteChildren: AdminDemandesRouteChildren = {
  AdminDemandesIdRoute: AdminDemandesIdRoute,
  AdminDemandesIndexRoute: AdminDemandesIndexRoute,
}

const AdminDemandesRouteWithChildren = AdminDemandesRoute._addFileChildren(
  AdminDemandesRouteChildren,
)

interface AdminScanRouteChildren {
  AdminScanMatchRoute: typeof AdminScanMatchRoute
  AdminScanIndexRoute: typeof AdminScanIndexRoute
}

const AdminScanRouteChildren: AdminScanRouteChildren = {
  AdminScanMatchRoute: AdminScanMatchRoute,
  AdminScanIndexRoute: AdminScanIndexRoute,
}

const AdminScanRouteWithChildren = AdminScanRoute._addFileChildren(
  AdminScanRouteChildren,
)

interface AdminRouteChildren {
  AdminDemandesRoute: typeof AdminDemandesRouteWithChildren
  AdminParcelsRoute: typeof AdminParcelsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminScanRoute: typeof AdminScanRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDemandesRoute: AdminDemandesRouteWithChildren,
  AdminParcelsRoute: AdminParcelsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminScanRoute: AdminScanRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HubRouteChildren {
  HubParcelsRoute: typeof HubParcelsRoute
  HubReceptionRoute: typeof HubReceptionRoute
  HubIndexRoute: typeof HubIndexRoute
  HubValisesIdRoute: typeof HubValisesIdRoute
  HubValisesIndexRoute: typeof HubValisesIndexRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubParcelsRoute: HubParcelsRoute,
  HubReceptionRoute: HubReceptionRoute,
  HubIndexRoute: HubIndexRoute,
  HubValisesIdRoute: HubValisesIdRoute,
  HubValisesIndexRoute: HubValisesIndexRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HubRoute: HubRouteWithChildren,
  DemandesIdRoute: DemandesIdRoute,
  DemandesIndexRoute: DemandesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
